services:
  postgres:
    image: postgres:16
    container_name: gerenciador_postgres
    restart: always
    environment:
      POSTGRES_DB: GerenciadorTarefasDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    container_name: gerenciador-backend
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=GerenciadorTarefasDB;Username=postgres;Password=admin
    ports:
      - "5000:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    container_name: gerenciador-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
